version: '3.6'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.0.10
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - hasura
      - postgres
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    ports:
      - "8080:8080" # Changed to avoid conflict

volumes:
  postgres_data: